{%- macro system_column_list() -%}
    {% set system_column = [
        "SYSTEM_VERSION",
        "SYSTEM_CURRENT_FLAG",
        "SYSTEM_START_DATE",
        "SYSTEM_END_DATE",
        "SYSTEM_CREATE_DATE",
        "SYSTEM_UPDATE_DATE",
        "SYSTEM_FILE_NAME",
        "SYSTEM_FILE_DATE",
        "SYSTEM_SOURCE_DATE",
        "SYSTEM_LANDING_DATE",
        "KEY_ROWHASH",
        "CDC_ID",
        "CDC_TIMESTAMP",
        "METADATA$ACTION_REFINE",
        "METADATA$ISUPDATE_REFINE",
        "METADATA$ROW_ID_REFINE",
        "METADATA$ACTION",
        "METADATA$ISUPDATE",
        "METADATA$ROW_ID",       
        "METADATA$ACTION_REFINED",
        "METADATA$ISUPDATE_REFINED",
        "METADATA$ROW_ID_REFINED",  
        "_ID",
        "_JOB_ID",
        "_CORRELATION_ID",
        "_SOURCE_ID",
        "_SOURCE_NAME",
        "_OBJECT_NAME",
        "_EVENT_TYPE",
        "_CREATED_AT",
        "_VERSION",
        "_ERROR_TYPE",
        "_ERROR_LEVEL",
        "_LOAD_DATE",
        "_FILENAME",
        "_PATH",       
        "_ROWHASH",
        "CreateTime",
        "key",
        "offset",
        "partition",
        "topic"
    ] %}
    {% do return(system_column) %}
{%- endmacro -%}
